{
 "title": "Agrego CPU PY",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "scale(derivative(stats.*.*.-docker.cpu_usage_system), 1e-7)"
    },
    {
     "target": "scale(derivative(stats.gauges.cadvisor.mataambre_gunicorn_1.cpu_usage_system), 1e-7)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.mataambre_gunicorn_1.memory_usage"
    }
   ]
  },
  {
   "title": "Artillery",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.artillery-gunicorn.requestsCompleted"
    }
   ]
  }
 ]
}