{
 "title": "TP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.mataambre_gunicorn_1.cpu_usage_system)"
    },
    {
     "target": "derivative(stats.gauges.cadvisor.mataambre_node_1.cpu_usage_system)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.mataambre_gunicorn_1.memory_usage"
    },
    {
     "target": "stats.gauges.cadvisor.mataambre_node_1.memory_usage"
    }
   ]
  },
  {
   "title": "Artillery Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.artillery-node.codes.*"
    },
    {
     "target": "stats.gauges.artillery-node.latency.max"
    },
    {
     "target": "stats.gauges.artillery-node.rps.mean"
    },
    {
     "target": "stats.gauges.artillery-node.pendingRequests"
    }
   ]
  },
  {
   "title": "Artillery Gunicorn",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.artillery-gunicorn.codes.*"
    },
    {
     "target": "scale(stats.gauges.artillery-gunicorn.latency.max, 0.01)"
    },
    {
     "target": "stats.gauges.artillery-gunicorn.rps.mean"
    },
    {
     "target": "stats.gauges.artillery-gunicorn.pendingRequests"
    }
   ]
  }
 ]
}